version: "3.7"

services:

  mongodb:
    image: mongo:4
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3-management
    environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mongo:
    driver: local